=== BaardBouvet/dtl-json-schemas/schemas/pipe.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$defs": {
        "dtl": {
            "expression": {
                "oneOf": [
                    {
                        "type": "string"
                    },
                    {
                        "type": "number"
                    },
                    {
                        "type": "boolean"
                    },
                    {
                        "type": "object"
                    },
                    {
                        "type": "array",
                        "items": {
                            "$ref": "#/$defs/dtl/expression"
                        }
                    }
                ],
                "defaultSnippets": [
                    {
                        "label": "Source",
                        "body": "_S.${0:some_source_property}"
                    },
                    {
                        "label": "Target",
                        "body": "_T.${0:some_target_property}"
                    },
                    {
                        "label": "Hops",
                        "body": [
                            "hops",
                            {
                                "datasets": [
                                    "${1:some_dataset} ${2:a}"
                                ],
                                "where": [
                                    [
                                        "eq",
                                        "_S.${3:some_source_property}",
                                        "$2.${4:some_other_property}"
                                    ]
                                ]
                            }
                        ]
                    },
                    {
                        "label": "Apply rule",
                        "body": [
                            "apply",
                            "${1:some_rule}",
                            "$0"
                        ]
                    },
                    {
                        "label": "List",
                        "body": [
                            "list",
                            "$0"
                        ]
                    }
                ]
            },
            "transformFunction": {
                "type": "array",
                "minLength": 1,
                "items": {
                    "$ref": "#/$defs/dtl/expression"
                },
                "defaultSnippets": [
                    {
                        "label": "Test",
                        "body": "$BLOCK_COMMENT_START Hello World $BLOCK_COMMENT_END"
                    },
                    {
                        "label": "New comment",
                        "body": [
                            "comment",
                            "${0:some comment}"
                        ]
                    },
                    {
                        "label": "Add property",
                        "body": [
                            "add",
                            "${1:some_target_property}",
                            "$0"
                        ]
                    },
                    {
                        "label": "Copy properties",
                        "body": [
                            "copy",
                            "${0:*}"
                        ]
                    }
                ]
            }
        },
        "transforms": {
            "dtl": {
                "type": "object",
                "required": [
                    "type",
                    "rules"
                ],
                "properties": {
                    "type": {
                        "const": "dtl"
                    },
                    "rules": {
                        "type": "object",
                        "patternProperties": {
                            "^.*$": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/$defs/dtl/transformFunction"
                                },
                                "minItems": 1
                            }
                        },
                        "required": [
                            "default"
                        ]
                    }
                }
            }
        },
        "sinks": {
            "dataset": {
                "type": "object",
                "properties": {
                    "dataset": {
                        "type": "string"
                    },
                    "type": {
                        "const": "dataset"
                    }
                }
            }
        },
        "sources": {
            "embedded": {
                "type": "object",
                "properties": {
                    "type": {
                        "const": "embedded"
                    },
                    "entities": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "_id": {
                                    "type": "string"
                                }
                            },
                            "defaultSnippets": [
                                {
                                    "label": "New embedded entity",
                                    "body": {
                                        "_id": "${0:some_entity_identifier}"
                                    }
                                }
                            ]
                        }
                    }
                },
                "required": [
                    "type",
                    "entities"
                ]
            },
            "dataset": {
                "type": "object",
                "properties": {
                    "type": {
                        "const": "dataset"
                    },
                    "dataset": {
                        "type": "string"
                    }
                },
                "required": [
                    "type",
                    "dataset"
                ]
            },
            "merge": {
                "type": "object",
                "properties": {
                    "type": {
                        "const": "merge"
                    },
                    "datasets": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "equality_sets": {
                        "type": "array"
                    },
                    "version": {
                        "type": "number"
                    }
                },
                "required": [
                    "type",
                    "datasets"
                ]
            }
        }
    },
    "$id": "pipe.json",
    "title": "Pipe",
    "description": "A pipe configuration with sources, transforms and sinks.",
    "type": "object",
    "properties": {
        "_id": {
            "description": "Pipe identifier, used as default sink dataset name unless overriden.",
            "type": "string"
        },
        "type": {
            "const": "pipe"
        },
        "sink": {
            "oneOf": [
                {
                    "$ref": "#/$defs/sinks/dataset"
                }
            ]
        },
        "source": {
            "markdownDescription": "See [sources](https://docs.sesam.io/hub/documentation/service-configuration/pipes/configuration-sources.html#source-section)",
            "oneOf": [
                {
                    "$ref": "#/$defs/sources/embedded"
                },
                {
                    "$ref": "#/$defs/sources/dataset"
                },
                {
                    "$ref": "#/$defs/sources/merge"
                }
            ],
            "defaultSnippets": [
                {
                    "label": "Insert dataset source",
                    "body": {
                        "type": "dataset",
                        "dataset": "${1:some_dataset}"
                    }
                },
                {
                    "label": "Insert embedded source",
                    "body": {
                        "type": "embedded",
                        "entities": [
                            "$0"
                        ]
                    }
                },
                {
                    "label": "Insert merge source",
                    "body": {
                        "type": "merge",
                        "datasets": [
                            "${1:dataset_a} ${2:a}",
                            "${3:dataset_b} ${4:b}"
                        ],
                        "equality_sets": [
                            [
                                "$2.${5:_id}",
                                "$4.${6:_id}"
                            ]
                        ],
                        "version": 2
                    }
                }
            ]
        },
        "transform": {
            "oneOf": [
                {
                    "$ref": "#/$defs/transforms/dtl"
                },
                {
                    "type": "array",
                    "items": {
                        "oneOf": {
                            "$ref": "#/$defs/transforms/dtl"
                        }
                    }
                }
            ],
            "defaultSnippets": [
                {
                    "label": "Insert DTL transform",
                    "body": {
                        "type": "dtl",
                        "rules": {
                            "default": [
                                "$0"
                            ]
                        }
                    }
                }
            ]
        }
    },
    "additionalProperties": false,
    "required": [
        "_id",
        "type",
        "source"
    ]
}

=== BaardBouvet/dtl-json-schemas/examples/pipes/person-with-orders.conf.json
{
    "_id": "person-with-orders",
    "type": "pipe",
    "source": {
        "type": "dataset",
        "dataset": "person"
    },
    "transform": {
        "type": "dtl",
        "rules": {
            "default": [
                [
                    "copy",
                    "_id"
                ],
                [
                    "add",
                    "type",
                    "customer"
                ],
                [
                    "add",
                    "name",
                    [
                        "upper",
                        [
                            "lower",
                            "_S.name"
                        ]
                    ]
                ],
                [
                    "add",
                    "orders",
                    [
                        "sorted",
                        "_.amount",
                        [
                            "apply-hops",
                            "order",
                            {
                                "datasets": [
                                    "orders o"
                                ],
                                "where": [
                                    [
                                        "eq",
                                        "_S._id",
                                        "o.cust_id"
                                    ]
                                ]
                            }
                        ]
                    ]
                ],
                [
                    "add",
                    "order_count",
                    [
                        "count",
                        "_T.orders"
                    ]
                ],
                [
                    "filter",
                    [
                        "gt",
                        "_T.order_count",
                        10
                    ]
                ]
            ],
            "order": [
                [
                    "copy",
                    "_id"
                ],
                [
                    "add",
                    "amount",
                    "_S.amount"
                ]
            ]
        }
    },
    "sink": {
        "type": "dataset",
        "dataset": "person-with-orders"
    }
}
